#!/bin/sh

echo sudo tunctl -u $(id -un) -t tap0
tunctl -u $(id -un) -t tap0

echo sudo ifconfig tap0 0.0.0.0 promisc up
ifconfig tap0 0.0.0.0 promisc up

echo sudo brctl addif br0 tap0
brctl addbr br0
brctl addif br0 tap0

echo brctl show
brctl show

ifconfig br0 192.168.7.20
